export const roleList = [
  {
    key: 'STUDENT',
    label: 'STUDENT',
  },
  {
    key: 'LECTURER',
    label: 'LECTURER',
  },
];


export const titleOptions = [
  {
    key: 'Mr',
    label: 'Mr',
  },
  {
    key: 'Ms',
    label: 'Ms',
  },
  {
    key: 'Mrs',
    label: 'Mrs',
  },
  {
    key: 'Dr',
    label: 'Dr',
  },
  {
    key: 'Professor',
    label: 'Professor',
  },
];

export const schoolList = [
  { key: 'Abia State Polytechnic Aba', label: 'Abia State Polytechnic Aba' },
  { key: 'Abia State University', label: 'Abia State University' },
  { key: 'Abubakar Tafawa Balewa University', label: 'Abubakar Tafawa Balewa University' },
  { key: 'Adamawa State Polytechnic Yola', label: 'Adamawa State Polytechnic Yola' },
  { key: 'Ahmadu Bello University', label: 'Ahmadu Bello University' },
  { key: 'Akwa Ibom State Polytechnic Ikot Osurua', label: 'Akwa Ibom State Polytechnic Ikot Osurua' },
  { key: 'Alvan Ikoku Federal College of Education Owerri', label: 'Alvan Ikoku Federal College of Education Owerri' },
  { key: 'Ambrose Alli University', label: 'Ambrose Alli University' },
  { key: 'American University of Nigeria', label: 'American University of Nigeria' },
  { key: 'Anambra State Polytechnic Mgbakwu', label: 'Anambra State Polytechnic Mgbakwu' },
  { key: 'Auchi Polytechnic Auchi', label: 'Auchi Polytechnic Auchi' },
  { key: 'Babcock University', label: 'Babcock University' },
  { key: 'Bauchi State Polytechnic Bauchi', label: 'Bauchi State Polytechnic Bauchi' },
  { key: 'Bayero University Kano', label: 'Bayero University Kano' },
  { key: 'Benue State University', label: 'Benue State University' },
  { key: 'Borno State Polytechnic Maiduguri', label: 'Borno State Polytechnic Maiduguri' },
  { key: 'Bowen University', label: 'Bowen University' },
  { key: 'College of Education Agbor', label: 'College of Education Agbor' },
  { key: 'College of Education Ikere Ekiti', label: 'College of Education Ikere Ekiti' },
  { key: 'Covenant University', label: 'Covenant University' },
  { key: 'Cross River State Polytechnic Calabar', label: 'Cross River State Polytechnic Calabar' },
  { key: 'Delta State Polytechnic Ogwashi Uku', label: 'Delta State Polytechnic Ogwashi Uku' },
  { key: 'Delta State University', label: 'Delta State University' },
  { key: 'Ebonyi State Polytechnic Abakaliki', label: 'Ebonyi State Polytechnic Abakaliki' },
  { key: 'Ekiti State Polytechnic Ado Ekiti', label: 'Ekiti State Polytechnic Ado Ekiti' },
  { key: 'Ekiti State University', label: 'Ekiti State University' },
  { key: 'Edo State Polytechnic Benin City', label: 'Edo State Polytechnic Benin City' },
  { key: 'Enugu State Polytechnic Enugu', label: 'Enugu State Polytechnic Enugu' },
  { key: 'Federal College of Education Abeokuta', label: 'Federal College of Education Abeokuta' },
  { key: 'Federal College of Education Asaba', label: 'Federal College of Education Asaba' },
  { key: 'Federal College of Education Bichi', label: 'Federal College of Education Bichi' },
  { key: 'Federal College of Education Eha Amufu', label: 'Federal College of Education Eha Amufu' },
  { key: 'Federal College of Education Gombe', label: 'Federal College of Education Gombe' },
  { key: 'Federal College of Education Kontagora', label: 'Federal College of Education Kontagora' },
  { key: 'Federal College of Education Minna', label: 'Federal College of Education Minna' },
  { key: 'Federal College of Education Obudu', label: 'Federal College of Education Obudu' },
  { key: 'Federal College of Education Okene', label: 'Federal College of Education Okene' },
  { key: 'Federal College of Education Pankshin', label: 'Federal College of Education Pankshin' },
  { key: 'Federal College of Education Yola', label: 'Federal College of Education Yola' },
  { key: 'Federal Polytechnic Bauchi', label: 'Federal Polytechnic Bauchi' },
  { key: 'Federal Polytechnic Bida', label: 'Federal Polytechnic Bida' },
  { key: 'Federal Polytechnic Damaturu', label: 'Federal Polytechnic Damaturu' },
  { key: 'Federal Polytechnic Ede', label: 'Federal Polytechnic Ede' },
  { key: 'Federal Polytechnic Idah', label: 'Federal Polytechnic Idah' },
  { key: 'Federal Polytechnic Ilaro', label: 'Federal Polytechnic Ilaro' },
  { key: 'Federal Polytechnic Kaura Namoda', label: 'Federal Polytechnic Kaura Namoda' },
  { key: 'Federal Polytechnic Mubi', label: 'Federal Polytechnic Mubi' },
  { key: 'Federal Polytechnic Nasarawa', label: 'Federal Polytechnic Nasarawa' },
  { key: 'Federal Polytechnic Nekede', label: 'Federal Polytechnic Nekede' },
  { key: 'Federal Polytechnic Offa', label: 'Federal Polytechnic Offa' },
  { key: 'Federal Polytechnic Oko', label: 'Federal Polytechnic Oko' },
  { key: 'Federal Polytechnic Uwana', label: 'Federal Polytechnic Uwana' },
  { key: 'Federal Polytechnic Yaba', label: 'Federal Polytechnic Yaba' },
  { key: 'Federal University Birnin Kebbi', label: 'Federal University Birnin Kebbi' },
  { key: 'Federal University Dutsin Ma', label: 'Federal University Dutsin Ma' },
  { key: 'Federal University Dutse', label: 'Federal University Dutse' },
  { key: 'Federal University Gashua', label: 'Federal University Gashua' },
  { key: 'Federal University Gusau', label: 'Federal University Gusau' },
  { key: 'Federal University Kashere', label: 'Federal University Kashere' },
  { key: 'Federal University Lafia', label: 'Federal University Lafia' },
  { key: 'Federal University Lokoja', label: 'Federal University Lokoja' },
  { key: 'Federal University Makurdi', label: 'Federal University Makurdi' },
  { key: 'Federal University Ndufu Alike Ikwo', label: 'Federal University Ndufu Alike Ikwo' },
  { key: 'Federal University Oye Ekiti', label: 'Federal University Oye Ekiti' },
  { key: 'Federal University of Agriculture Abeokuta', label: 'Federal University of Agriculture Abeokuta' },
  { key: 'Federal University of Agriculture Makurdi', label: 'Federal University of Agriculture Makurdi' },
  { key: 'Federal University of Petroleum Resources Effurun', label: 'Federal University of Petroleum Resources Effurun' },
  { key: 'Federal University of Technology Akure', label: 'Federal University of Technology Akure' },
  { key: 'Federal University of Technology Minna', label: 'Federal University of Technology Minna' },
  { key: 'Federal University of Technology Owerri', label: 'Federal University of Technology Owerri' },
  { key: 'Federal University of Technology Yola', label: 'Federal University of Technology Yola' },
  { key: 'Federal University Wukari', label: 'Federal University Wukari' },
  { key: 'Gombe State Polytechnic Bajoga', label: 'Gombe State Polytechnic Bajoga' },
  { key: 'Gombe State University', label: 'Gombe State University' },
  { key: 'Imo State Polytechnic Umuagwo', label: 'Imo State Polytechnic Umuagwo' },
  { key: 'Imo State University', label: 'Imo State University' },
  { key: 'Jigawa State Polytechnic Dutse', label: 'Jigawa State Polytechnic Dutse' },
  { key: 'Kaduna State University', label: 'Kaduna State University' },
  { key: 'Kano State University of Science and Technology', label: 'Kano State University of Science and Technology' },
  { key: 'Kogi State University', label: 'Kogi State University' },
  { key: 'Ladoke Akintola University of Technology', label: 'Ladoke Akintola University of Technology' },
  { key: 'Lagos State University', label: 'Lagos State University' },
  { key: 'National Open University of Nigeria', label: 'National Open University of Nigeria' },
  { key: 'Nasarawa State University', label: 'Nasarawa State University' },
  { key: 'Obafemi Awolowo University', label: 'Obafemi Awolowo University' },
  { key: 'Olabisi Onabanjo University', label: 'Olabisi Onabanjo University' },
  { key: 'Ondo State University of Science and Technology', label: 'Ondo State University of Science and Technology' },
  { key: 'Osun State University', label: 'Osun State University' },
  { key: 'Plateau State University', label: 'Plateau State University' },
  { key: "Redeemer's University", label: "Redeemer's University" },
  { key: 'Rivers State University', label: 'Rivers State University' },
  { key: 'Sokoto State University', label: 'Sokoto State University' },
  { key: 'Tai Solarin College of Education Ijebu Ode', label: 'Tai Solarin College of Education Ijebu Ode' },
  { key: 'Tai Solarin University of Education', label: 'Tai Solarin University of Education' },
  { key: 'Taraba State University', label: 'Taraba State University' },
  { key: 'University of Benin', label: 'University of Benin' },
  { key: 'University of Calabar', label: 'University of Calabar' },
  { key: 'University of Ibadan', label: 'University of Ibadan' },
  { key: 'University of Ilorin', label: 'University of Ilorin' },
  { key: 'University of Jos', label: 'University of Jos' },
  { key: 'University of Lagos', label: 'University of Lagos' },
  { key: 'University of Nigeria Nsukka', label: 'University of Nigeria Nsukka' },
  { key: 'University of Port Harcourt', label: 'University of Port Harcourt' },
  { key: 'Yobe State University', label: 'Yobe State University' },
  { key: 'Zamfara State University', label: 'Zamfara State University' },
];
